- name: 关闭防火墙
  service: name=firewalld state=stopped enabled=false

- name: 关闭 selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: 使selinux即时生效
  shell: setenforce 0
  ignore_errors: True

- name: 修改时区为上海
  copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime

- name: 安装 ntpdate
  yum: name=ntpdate state=present

- name: 同步时间
  shell: ntpdate time.windows.com

- name: 创建临时目录，用于存放ansible使用到的文件
  file: path={{ tmp_dir }} state=directory mode='0755'

- name: 创建安装软件路径
  file: path={{ installed_dir }} state=directory mode='0755'

- name: 配置ip和hostname的映射到hosts.tmp
  template: src=hosts.j2 dest={{ tmp_dir }}/hosts.tmp

# 由于我所使用的私有云在每次重启后都会重置/etc/hosts文件，因此每次操作前先去掉加上的属性，让其可写入。
- name: remove a attribute from /etc/hosts
  shell: chattr -a /etc/hosts

- name: 在/etc/hosts文件末尾追加ip和hostname映射
  blockinfile:
    block: "{{ lookup('file', '{{ tmp_dir }}/hosts.tmp') }}"
    dest: /etc/hosts
    backup: yes

# 由于我所使用的私有云在每次重启后都会重置/etc/hosts文件，因此加上一个属性不让其更改
- name: add a attribute to /etc/hosts
  shell: chattr +a /etc/hosts

